"""Write onionwatch/langnames_data.py: the name of every app language in every app
language, from Unicode CLDR (so nobody translates language names by hand). The
Language picker shows them under each language's own name ("Deutsch / German").

Run it after adding a catalog (onionwatch/lang/*.json):

    .venv\\Scripts\\python scripts\\make_langnames.py

It fetches CLDR's language and territory names from jsDelivr (a few seconds) and
rewrites the data file. The same source and rules as Onion Board's
scripts/make_langnames.py, so both show the same names.
"""
from __future__ import annotations

import json
import pprint
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLDR = "https://cdn.jsdelivr.net/npm/cldr-localenames-full@46.0.0/main/{loc}/{what}.json"
OUT = ROOT / "onionwatch" / "langnames_data.py"

# app language -> CLDR locale, where they differ
UI_TO_CLDR = {"zh-CN": "zh", "zh-TW": "zh-Hant", "pt-BR": "pt"}
# language named -> CLDR language code, when CLDR names it better on its own
# (Traditional Chinese by its script, Simplified as plain Chinese)
NAMED_TO_CLDR = {"zh-TW": "zh-Hant", "zh-CN": "zh-Hans", "nb": "nb"}


def fetch(loc: str, what: str) -> dict:
    with urllib.request.urlopen(CLDR.format(loc=loc, what=what), timeout=30) as r:
        main = json.load(r)["main"]
    return next(iter(main.values()))["localeDisplayNames"]


def name_in(code: str, langs: dict, regions: dict, pattern: str) -> str:
    """CLDR's own name; "Language (Region)" for a region, so both Portugueses sit
    together; Chinese by its script."""
    cldr = NAMED_TO_CLDR.get(code, code)
    base, _, region = code.partition("-")
    if cldr in langs and (cldr != code or not region):
        return langs[cldr]
    if region and base in langs and region in regions:
        return pattern.replace("{0}", langs[base]).replace("{1}", regions[region])
    return langs.get(base, code)


def main() -> None:
    ui = ["en"] + sorted(p.stem for p in (ROOT / "onionwatch" / "lang").glob("*.json"))
    table: dict[str, dict[str, str]] = {}
    for lang in ui:
        loc = UI_TO_CLDR.get(lang, lang)
        names = fetch(loc, "languages")
        regions = fetch(loc, "territories")["territories"]
        pattern = fetch(loc, "localeDisplayNames")["localeDisplayPattern"]["localePattern"]
        # a name starts with a capital, even where CLDR writes "portugais"
        table[lang] = {c: (n := name_in(c, names["languages"], regions, pattern))[:1].upper()
                       + n[1:] for c in ui}
        print(lang, "ok", flush=True)
    OUT.write_text('"""Generated by scripts/make_langnames.py from Unicode CLDR 46 (Unicode '
                   'License\nv3). Do not edit: rerun the script. App language -> app language '
                   '-> its name."""\n'
                   f"NAMES = {pprint.pformat(table, width=90, sort_dicts=True)}\n",
                   encoding="utf-8", newline="\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
